Update brunch-toolkit
correct typo

diff --git a/brunch-toolkit b/brunch-toolkit
--- a/brunch-toolkit
+++ b/brunch-toolkit
@@ -605,7 +605,7 @@ echo "Version: $TOOLVER"
     # Unzip selection
         echo "Unzipping archive, please wait..."
         BSDIR=$(echo "$BOOTSPLASH" | sed -e s/.zip//)
-        bdstar -xf "$BOOTSPLASH" -C $DOWNLOADS/"$BSDIR" || { echo "[ERROR] Unable to unzip animation archive" ; cleanexit ; }
+        bsdtar -xf "$BOOTSPLASH" -C $DOWNLOADS/"$BSDIR" || { echo "[ERROR] Unable to unzip animation archive" ; cleanexit ; }
         sudo cp $DOWNLOADS/$BSDIR/boot_splash_frame*.png /usr/share/chromeos-assets/images_100_percent || { echo "[ERROR] Unable to apply boot animation" ; cleanexit ; }
         sudo cp $DOWNLOADS/$BSDIR/boot_splash_frame*.png /usr/share/chromeos-assets/images_200_percent 2> /dev/null
         mkdir /usr/local/bin/brunch-toolkit-assets 2> /dev/null
@@ -902,7 +902,7 @@ echo "Version: $TOOLVER"
     checkunzip(){
     if [[ "$CHROME" =~ .*"zip".* ]] ; then
     echo "Unzipping selected file, please wait..."
-            bdstar -xf "$CHROME" || { echo "[ERROR] Unzip failed!" ; echo "Try another file." ; echo "If this keeps happening, please try to unzip the file manually." ; getcros ; }
+            bsdtar -xf "$CHROME" || { echo "[ERROR] Unzip failed!" ; echo "Try another file." ; echo "If this keeps happening, please try to unzip the file manually." ; getcros ; }
             TMPNZIP=$CHROME
             rm "$CHROME"
             CHROME=${TMPNZIP%.zip}
