Update brunch-toolkit

diff --git a/brunch-toolkit b/brunch-toolkit
--- a/brunch-toolkit
+++ b/brunch-toolkit
@@ -905,7 +905,11 @@ echo "Version: $TOOLVER"
     checkunzip(){
     if [[ "$CHROME" =~ .*"zip".* ]] ; then
     echo "Unzipping selected file, please wait..."
+        if [ "$LINUX" == "true" ] ; then
+            unzip "$CHROME" || { echo "[ERROR] Unzip failed!" ; echo "Try another file." ; echo "If this keeps happening, please try to unzip the file manually." ; getcros ; }
+        else
             bsdtar -xf "$CHROME" || { echo "[ERROR] Unzip failed!" ; echo "Try another file." ; echo "If this keeps happening, please try to unzip the file manually." ; getcros ; }
+        fi
             TMPNZIP=$CHROME
             rm "$CHROME"
             CHROME=${TMPNZIP%.zip}
@@ -1030,7 +1034,11 @@ echo "Version: $TOOLVER"
         echo "Chrome OS recovery downloaded! Unzipping, please wait..."
         echo ""
         CHROME="$(find *$RECOVERYTODOWNLOAD*.bin.zip 2> /dev/null | sort -r | head -1)"
-        bsdtar -xf "$CHROME"
+        if [ "$LINUX" == "true" ] ; then
+            unzip "$CHROME"
+        else
+            bsdtar -xf "$CHROME"
+        fi
         CROS="$(find *$RECOVERYTODOWNLOAD*.bin 2> /dev/null | sort -r | head -1)"
         rm "$CHROME"
         selectcrosoffline
